### ISSUE TITLE
how to solve

### ISSUE THREAD

**Issue by saran110313** [gruntjs/grunt#1298]
Express
500 SyntaxError: Unexpected token (474:0)
at raise (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:298:15)
at unexpected (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1284:5)
at parseExprAtom (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:2049:7)
at parseExprSubscripts (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1912:28)
at parseMaybeUnary (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1896:16)
at parseExprOps (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1854:24)
at parseMaybeConditional (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1839:16)
at parseMaybeAssign (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1823:16)
at parseExpression (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1809:16)
at parseStatement (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1501:38)
at parseBlock (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1738:18)

**Comment by sindresorhus** [comment]
http://stackoverflow.com/questions/ask
