### ISSUE TITLE
Grunt aborts build by showing the below error.

### ISSUE THREAD

**Issue by mrtinkz** [gruntjs/grunt#1426]
When it happens ?
~ grunt build --stack

What happens ?
Please see below

Running "htmlmin" task
Warning: undefined is not a function Use --force to continue.
TypeError: undefined is not a function
    at C:\opt\workspace\temp\node_modules\grunt\lib\grunt\file.js:55:29
    at Array.forEach (native)
    at processPatterns (C:\opt\workspace\temp\node_modules\grunt\lib\grunt\file.js:53:34)
    at Object.file.expand (C:\opt\workspace\temp\node_modules\grunt\lib\grunt\file.js:110:17)
    at Object.<anonymous> (C:\opt\workspace\temp\node_modules\grunt-htmlmin\tasks\htmlmin.js:57:36)
    at Object.thisTask.fn (C:\opt\workspace\temp\node_modules\grunt\lib\grunt\task.js:82:16)
    at Object.task.fn (C:\opt\workspace\temp\node_modules\jit-grunt\lib\jit-grunt.js:122:30)
    at Object.<anonymous> (C:\opt\workspace\temp\node_modules\grunt\lib\util\task.js:301:30)
    at Task.runTaskFn (C:\opt\workspace\temp\node_modules\grunt\lib\util\task.js:251:24)
    at Task.<anonymous> (C:\opt\workspace\temp\node_modules\grunt\lib\util\task.js:300:12)

Aborted due to warnings.

**Comment by vladikoff** [comment]
Something is wrong with your htmlmin configuration. 

Ref https://github.com/gruntjs/grunt/blob/master/lib/grunt/file.js#L55

Please post your extended config in a StackOverflow question.
