### ISSUE TITLE
Fatal error: spawn EACCES

### ISSUE THREAD

**Issue by usergyt** [gruntjs/grunt#1434]
Running "connect:livereload" (connect) task
Started connect web server on http://localhost:9000
Fatal error: spawn EACCES

What is the cause of the specific？？

**Comment by usergyt** [comment]
Started connect web server on http://localhost:9000
Fatal error: spawn EACCES
Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:362:9)
    at module.exports (/node/myapps/node_modules/opn/index.js:58:24)
    at Server.<anonymous> (/node/myapps/node_modules/grunt-contrib-connect/tasks/connect.js:192:17)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1262:10)
    at nextTickCallbackWith1Arg (node.js:463:9)
    at process._tickCallback (node.js:385:17)

**Comment by shama** [comment]
Most likely because you already have an existing `9000` port open and it doesn't have access to open another.
