### ISSUE TITLE
Grunt becomes an unkillable process

### ISSUE THREAD

**Issue by Sam2304** [gruntjs/grunt#1441]
Hi folks,

I have a somewhat complex scenario in which I have an unkillable grunt process hogging a core on my machine.

How I got here:
I have a web service based on top of [SailsJS.](https://github.com/balderdashy/sails)  By default sailsJS implementations include a number of grunt tasks to assist with getting things up and running.

I have a [Docker](https://www.docker.com/) image that houses the SailsJS backend, which is run and torn-down by a Jenkins CI server.

The majority of the time, this issue doesn't arise, I have a good handful of CI builds that executed flawlessly.  However twice now I've come back to the CI to see its waiting on a Docker stop command for the Container running the SailsJS backend.

```
docker stop c70548b7ff45746de88596b4b25ca53672f26d8d0c776132c82de7f4f832085d
```
At this point I noticed a cores worth of CPU usage, and ran a top to have a look:
```
7951 root      20   0  913660  49844  14676 R 100.0  0.3 911:07.15 grunt  
```
This was sat at the top of the list.  I subsequently tried a variety of kill signals to 7951, none of which had any effect.

I then had a look for a parent process, which was NPM:
```
ps -elf | grep [7]702
4 Z root      7702     1  0  80   0 -     0 -      Feb03 ?        00:00:00 [npm] <defunct>
0 R root      7951  7702 99  80   0 - 228415 -     Feb03 ?        15:16:50 grunt 
```

Trying to kill [npm] was also ineffective.  Originally [npm] was parented to the Docker Server running on the host.  By shutting down the Docker server, [npm] was re-attached to SystemD for zombie collection.

I have a sneaking suspicion that whatever is wrong is because grunt hadn't finished running its task when docker sent an exit signal, so I'm guessing that it might be trying to operate on something that no longer exists?

Having a look at what is open using ```htop``` and then hitting ```l``` on grunt shows what it has open:
```
FD TYPE     DEVICE       SIZE       NODE NAME
    0 sock        0x8                211001 can't identify protocol
    1 sock        0x8                211003 can't identify protocol
    2 sock        0x8                211005 can't identify protocol
    3 sock        0x8                211007 can't identify protocol
    4 FIFO        0x9                210380 pipe
    5 FIFO        0x9                210380 pipe
    6 0000        0xa          0       7715 anon_inode
    7 FIFO        0x9                210381 pipe
    8 FIFO        0x9                210381 pipe
    9 0000        0xa          0       7715 anon_inode
   10  CHR       0x94                196432 /dev/null
  cwd  DIR       0x82       4096         13 /usr/src/app
  mem  REG       0x82                    39 /lib/x86_64-linux-gnu/ld-2.19.so (stat: No such file or directory)
  mem  REG       0x82                    42 /lib/x86_64-linux-gnu/libc-2.19.so (stat: No such file or directory)
  mem  REG       0x82                    48 /lib/x86_64-linux-gnu/libdl-2.19.so (stat: No such file or directory)
  mem  REG       0x82                    50 /lib/x86_64-linux-gnu/librt-2.19.so (stat: No such file or directory)
  mem  REG       0x82                    54 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20 (path dev=252,0, inode=63705795)
  mem  REG       0x82                    56 /lib/x86_64-linux-gnu/libm-2.19.so (stat: No such file or directory)
  mem  REG       0x82                    57 /lib/x86_64-linux-gnu/libgcc_s.so.1 (path dev=252,0, inode=23598344)
  mem  REG       0x82                    59 /lib/x86_64-linux-gnu/libpthread-2.19.so (stat: No such file or directory)
  rtd  DIR       0x82       4096          2 /
  txt  REG       0x82   24749451         46 /usr/local/bin/node
```

There are a selection of grunt tasks run by sails, I'm happy to do a bit of digging and see if I can find which one was run, but the container logs show no information beyond a call to `node app.js`, which isn't particularly helpful.

I'm not sure if the above information is useful to anyone. I'm happy to leave it cooking on one of my cores if anyone is interested in trying to fix it without a reboot (I have some VMs running that I would really rather not reboot...)

**Comment by Sam2304** [comment]
Tracing where SailsJS went, `app.js` eventually calls `Sails.lift(rc('sails'))`.  I believe this eventually calls grunt on the `default.js` grunt task:
```
module.exports = function(grunt) {
  grunt.registerTask('default', ['compileAssets', 'linkAssets',  'watch'])
}
```
compileAssets.js:
```
module.exports = function(grunt) {
  grunt.registerTask('compileAssets', [
  'clean:dev',
  'jst:dev',
  'less:dev',
  'copy:dev',
  'coffee:dev',
  ])
}
```
linkAssets.js:
```
module.exports = function(grunt) {
  grunt.registerTask('linkAssets', [
  'sails-linker:devJs',
  'sails-linker:devStyles',
  'sails-linker:devTpl',
  'sails-linker:devJsJade',
  'sails-linker:devStylesJade',
  'sails-linker:devTplJade',
  ])
}
```
watch:
```
module.exports = function(grunt) {

  grunt.config.set('watch', {
    api: {

    // API files to watch:
      files: ['api/**/*', '!**/node_modules/**'],
    },
    assets: {

    // Assets to watch:
      files: ['assets/**/*', 'tasks/pipeline.js', '!**/node_modules/**'],

      // When assets are changed:
      tasks: ['syncAssets' , 'linkAssets'],
    },
  })

  grunt.loadNpmTasks('grunt-contrib-watch')
}
```

sails-linker.js:
```
module.exports = function(grunt) {

  grunt.config.set('sails-linker', {
    devJs: {
      options: {
        startTag: '<!--SCRIPTS-->',
        endTag: '<!--SCRIPTS END-->',
        fileTmpl: '<script src="%s"></script>',
        appRoot: '.tmp/public',
      },
      files: {
        '.tmp/public/**/*.html': require('../pipeline').jsFilesToInject,
        'views/**/*.html': require('../pipeline').jsFilesToInject,
        'views/**/*.ejs': require('../pipeline').jsFilesToInject,
      },
    },

    devJsRelative: {
      options: {
        startTag: '<!--SCRIPTS-->',
        endTag: '<!--SCRIPTS END-->',
        fileTmpl: '<script src="%s"></script>',
        appRoot: '.tmp/public',
        relative: true,
      },
      files: {
        '.tmp/public/**/*.html': require('../pipeline').jsFilesToInject,
        'views/**/*.html': require('../pipeline').jsFilesToInject,
        'views/**/*.ejs': require('../pipeline').jsFilesToInject,
      },
    },

    prodJs: {
      options: {
        startTag: '<!--SCRIPTS-->',
        endTag: '<!--SCRIPTS END-->',
        fileTmpl: '<script src="%s"></script>',
        appRoot: '.tmp/public',
      },
      files: {
        '.tmp/public/**/*.html': ['.tmp/public/min/production.min.js'],
        'views/**/*.html': ['.tmp/public/min/production.min.js'],
        'views/**/*.ejs': ['.tmp/public/min/production.min.js'],
      },
    },

    prodJsRelative: {
      options: {
        startTag: '<!--SCRIPTS-->',
        endTag: '<!--SCRIPTS END-->',
        fileTmpl: '<script src="%s"></script>',
        appRoot: '.tmp/public',
        relative: true,
      },
      files: {
        '.tmp/public/**/*.html': ['.tmp/public/min/production.min.js'],
        'views/**/*.html': ['.tmp/public/min/production.min.js'],
        'views/**/*.ejs': ['.tmp/public/min/production.min.js'],
      },
    },

    devStyles: {
      options: {
        startTag: '<!--STYLES-->',
        endTag: '<!--STYLES END-->',
        fileTmpl: '<link rel="stylesheet" href="%s">',
        appRoot: '.tmp/public',
      },

      files: {
        '.tmp/public/**/*.html': require('../pipeline').cssFilesToInject,
        'views/**/*.html': require('../pipeline').cssFilesToInject,
        'views/**/*.ejs': require('../pipeline').cssFilesToInject,
      },
    },

    devStylesRelative: {
      options: {
        startTag: '<!--STYLES-->',
        endTag: '<!--STYLES END-->',
        fileTmpl: '<link rel="stylesheet" href="%s">',
        appRoot: '.tmp/public',
        relative: true,
      },

      files: {
        '.tmp/public/**/*.html': require('../pipeline').cssFilesToInject,
        'views/**/*.html': require('../pipeline').cssFilesToInject,
        'views/**/*.ejs': require('../pipeline').cssFilesToInject,
      },
    },

    prodStyles: {
      options: {
        startTag: '<!--STYLES-->',
        endTag: '<!--STYLES END-->',
        fileTmpl: '<link rel="stylesheet" href="%s">',
        appRoot: '.tmp/public',
      },
      files: {
        '.tmp/public/index.html': ['.tmp/public/min/production.min.css'],
        'views/**/*.html': ['.tmp/public/min/production.min.css'],
        'views/**/*.ejs': ['.tmp/public/min/production.min.css'],
      },
    },

    prodStylesRelative: {
      options: {
        startTag: '<!--STYLES-->',
        endTag: '<!--STYLES END-->',
        fileTmpl: '<link rel="stylesheet" href="%s">',
        appRoot: '.tmp/public',
        relative: true,
      },
      files: {
        '.tmp/public/index.html': ['.tmp/public/min/production.min.css'],
        'views/**/*.html': ['.tmp/public/min/production.min.css'],
        'views/**/*.ejs': ['.tmp/public/min/production.min.css'],
      },
    },

    // Bring in JST template object
    devTpl: {
      options: {
        startTag: '<!--TEMPLATES-->',
        endTag: '<!--TEMPLATES END-->',
        fileTmpl: '<script type="text/javascript" src="%s"></script>',
        appRoot: '.tmp/public',
      },
      files: {
        '.tmp/public/index.html': ['.tmp/public/jst.js'],
        'views/**/*.html': ['.tmp/public/jst.js'],
        'views/**/*.ejs': ['.tmp/public/jst.js'],
      },
    },

    devJsJade: {
      options: {
        startTag: '// SCRIPTS',
        endTag: '// SCRIPTS END',
        fileTmpl: 'script(src="%s")',
        appRoot: '.tmp/public',
      },
      files: {
        'views/**/*.jade': require('../pipeline').jsFilesToInject,
      },
    },

    devJsRelativeJade: {
      options: {
        startTag: '// SCRIPTS',
        endTag: '// SCRIPTS END',
        fileTmpl: 'script(src="%s")',
        appRoot: '.tmp/public',
        relative: true,
      },
      files: {
        'views/**/*.jade': require('../pipeline').jsFilesToInject,
      },
    },

    prodJsJade: {
      options: {
        startTag: '// SCRIPTS',
        endTag: '// SCRIPTS END',
        fileTmpl: 'script(src="%s")',
        appRoot: '.tmp/public',
      },
      files: {
        'views/**/*.jade': ['.tmp/public/min/production.min.js'],
      },
    },

    prodJsRelativeJade: {
      options: {
        startTag: '// SCRIPTS',
        endTag: '// SCRIPTS END',
        fileTmpl: 'script(src="%s")',
        appRoot: '.tmp/public',
        relative: true,
      },
      files: {
        'views/**/*.jade': ['.tmp/public/min/production.min.js'],
      },
    },

    devStylesJade: {
      options: {
        startTag: '// STYLES',
        endTag: '// STYLES END',
        fileTmpl: 'link(rel="stylesheet", href="%s")',
        appRoot: '.tmp/public',
      },

      files: {
        'views/**/*.jade': require('../pipeline').cssFilesToInject,
      },
    },

    devStylesRelativeJade: {
      options: {
        startTag: '// STYLES',
        endTag: '// STYLES END',
        fileTmpl: 'link(rel="stylesheet", href="%s")',
        appRoot: '.tmp/public',
        relative: true,
      },

      files: {
        'views/**/*.jade': require('../pipeline').cssFilesToInject,
      },
    },

    prodStylesJade: {
      options: {
        startTag: '// STYLES',
        endTag: '// STYLES END',
        fileTmpl: 'link(rel="stylesheet", href="%s")',
        appRoot: '.tmp/public',
      },
      files: {
        'views/**/*.jade': ['.tmp/public/min/production.min.css'],
      },
    },

    prodStylesRelativeJade: {
      options: {
        startTag: '// STYLES',
        endTag: '// STYLES END',
        fileTmpl: 'link(rel="stylesheet", href="%s")',
        appRoot: '.tmp/public',
        relative: true,
      },
      files: {
        'views/**/*.jade': ['.tmp/public/min/production.min.css'],
      },
    },

    // Bring in JST template object
    devTplJade: {
      options: {
        startTag: '// TEMPLATES',
        endTag: '// TEMPLATES END',
        fileTmpl: 'script(type="text/javascript", src="%s")',
        appRoot: '.tmp/public',
      },
      files: {
        'views/**/*.jade': ['.tmp/public/jst.js'],
      },
    },
  })

  grunt.loadNpmTasks('grunt-sails-linker')
}
```

My guess is its something related to grunt watching something and then breaking when Docker issues a stop command...

**Comment by Sam2304** [comment]
Looks like it might be a problem caused by my testing.  After building the docker image from the latest code, I run a quick integrity check to make sure the container will in fact run. It might not if I've borked something somewhere, in which case there is no point running the rest of the build...

Stepping through what the CI does manually results in an error due to no instance of a Database container running:
```
root@fbfd6f8ed189:/usr/src/app# npm start
npm info it worked if it ends with ok
npm info using npm@2.14.12
npm info using node@v4.2.6
npm info prestart umc-web-ui@0.0.1
npm info start umc-web-ui@0.0.1

> umc-web-ui@0.0.1 start /usr/src/app
> node app.js

error: A hook (`orm`) failed to load!
error: Error: Failed to connect to MongoDB.  Are you sure your configured Mongo instance is running?
 Error details:
{ [MongoError: getaddrinfo ENOTFOUND www-mongo www-mongo:27017]
  name: 'MongoError',
  message: 'getaddrinfo ENOTFOUND www-mongo www-mongo:27017' }
    at _createError (/usr/src/app/node_modules/sails-mongo/lib/adapter.js:103:23)
    at /usr/src/app/node_modules/sails-mongo/lib/adapter.js:106:13
    at /usr/src/app/node_modules/sails-mongo/lib/connection.js:25:20
    at /usr/src/app/node_modules/sails-mongo/node_modules/mongodb/lib/mongo_client.js:276:20
    at /usr/src/app/node_modules/sails-mongo/node_modules/mongodb/lib/db.js:224:14
    at null.<anonymous> (/usr/src/app/node_modules/sails-mongo/node_modules/mongodb/lib/server.js:234:9)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at null.<anonymous> (/usr/src/app/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:269:68)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at null.<anonymous> (/usr/src/app/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:81:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13) { [Error: Failed to connect to MongoDB.  Are you sure your configured Mongo instance is running?
 Error details:
{ [MongoError: getaddrinfo ENOTFOUND www-mongo www-mongo:27017]
  name: 'MongoError',
  message: 'getaddrinfo ENOTFOUND www-mongo www-mongo:27017' }]
  originalError: 
   { [MongoError: getaddrinfo ENOTFOUND www-mongo www-mongo:27017]
     name: 'MongoError',
     message: 'getaddrinfo ENOTFOUND www-mongo www-mongo:27017' } }
```

In this instance however sending `cntrl+c` successfully kills everything, but I wonder if a stoop signal sent to docker at the wrong moment might be what is causing things.

Still, I'm surprised I ended up with a completely unkillable process... (Pretty sure its something stupid I've done though)

**Comment by shama** [comment]
Could you reduce the issue and show how this is an issue with Grunt core?

**Comment by shama** [comment]
Could you reduce the issue and show how this is an issue with Grunt core?

**Comment by Sam2304** [comment]
@shama Sure thing, primary reason I put this here was based on an un-killable grunt process eating a CPU core.  I'll edit down as soon as I know more. Apologies for the verbosity.

**Comment by Sam2304** [comment]
I haven't been able to replicate the issue or track down where it could have come from.  I'll close this since there is no progress to report. (Sorry to spam your issues list!)
