### ISSUE TITLE
Grunt Cli not installing 

### ISSUE THREAD

**Issue by jagvirsingh5** [gruntjs/grunt#1513]
Here is the debug.log 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'grunt-cli' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'grunt-cli', null ]
7 verbose cache add spec grunt-cli
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'grunt-cli',
8 silly cache add   scope: null,
8 silly cache add   name: 'grunt-cli',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed grunt-cli@latest
10 verbose addNamed "latest" is being treated as a dist-tag for grunt-cli
11 info addNameTag [ 'grunt-cli', 'latest' ]
12 silly mapToRegistry name grunt-cli
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://artifactory.nexus.commercehub.com/artifactory/api/npm/npm-local
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'grunt-cli',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'grunt-cli',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri http://artifactory.nexus.commercehub.com/artifactory/api/npm/npm-local/grunt-cli
17 verbose addNameTag registry:http://artifactory.nexus.commercehub.com/artifactory/api/npm/npm-local/grunt-cli not in flight; fetching
18 verbose request uri http://artifactory.nexus.commercehub.com/artifactory/api/npm/npm-local/grunt-cli
19 verbose request always-auth set; sending authorization
20 info attempt registry request try #1 at 10:38:10 AM
21 verbose request id ba3395076951df39
22 http request GET http://artifactory.nexus.commercehub.com/artifactory/api/npm/npm-local/grunt-cli
23 http 404 http://artifactory.nexus.commercehub.com/artifactory/api/npm/npm-local/grunt-cli
24 verbose headers { server: 'Artifactory/3.5.3',
24 verbose headers   'x-artifactory-id': '9cd8fb93c7c71a3a:-bde00ef:15315dacdd7:-8000',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   'transfer-encoding': 'chunked',
24 verbose headers   date: 'Tue, 03 May 2016 14:38:09 GMT' }
25 silly get cb [ 404,
25 silly get   { server: 'Artifactory/3.5.3',
25 silly get     'x-artifactory-id': '9cd8fb93c7c71a3a:-bde00ef:15315dacdd7:-8000',
25 silly get     'content-type': 'application/json',
25 silly get     'transfer-encoding': 'chunked',
25 silly get     date: 'Tue, 03 May 2016 14:38:09 GMT' } ]
26 verbose stack Error: 404 Not Found: grunt-cli
26 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
26 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:250:14)
26 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
26 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
26 verbose stack     at emitTwo (events.js:87:13)
26 verbose stack     at Request.emit (events.js:172:7)
26 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
26 verbose stack     at emitOne (events.js:82:20)
26 verbose stack     at Request.emit (events.js:169:7)
26 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
27 verbose statusCode 404
28 verbose pkgid grunt-cli
29 verbose cwd /Users/jsingh
30 error Darwin 15.4.0
31 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
32 error node v4.4.3
33 error npm  v2.15.1
34 error code E404
35 error 404 Not Found: grunt-cli
35 error 404
35 error 404 'grunt-cli' is not in the npm registry.
35 error 404 You should bug the author to publish it (or use the name yourself!)
35 error 404
35 error 404 Note that you can also install from a
35 error 404 tarball, folder, http url, or git url.
36 verbose exit [ 1, true ]
```

**Comment by vladikoff** [comment]
Looks like a problem with whatever this is: `http request GET http://artifactory.nexus.commercehub.com/artifactory/api/npm/npm-local/grunt-cli`

Your custom npm mirror or something
