### ISSUE TITLE
Cannot find module 'brace-expansion'

### ISSUE THREAD

**Issue by artuska** [gruntjs/grunt#1515]
```
E:\Dropbox\flat.fm>grunt
module.js:442
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\node_modules\grunt-cli\node_modules\minimatch\minimatch.js:10:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I have `brace-expansion` in my `E:\node_modules` folder.

```
node@6.2.0
npm@3.9.2
```

**Comment by shama** [comment]
It sounds like `grunt-cli` didn't get installed properly (could be related to having Dropbox managing that folder). Try `npm i grunt-cli -g` again.

**Comment by artuska** [comment]
@shama Thank you! (No-no, Dropbox is not related to this issue at all :)

**Comment by sundarsy** [comment]
How is this got fixed? I am facing the same issue.

**Comment by davide-casiraghi** [comment]
I had the same issue and solved running:

> npm i brace-expansion
