### ISSUE TITLE
Problem with Strut and "grunt server" command

### ISSUE THREAD

**Issue by HogiQuin** [gruntjs/grunt#1517]
Hello, I have a little problem, is mi first time with node and I found this web app that make slides like power point, but the instructions to install say that I should put "grunt server" for run the local server in http://localhost:9000 - but when I put that in the console, this happen :

sonnica@desarrollo:~/Escritorio/Strut$ grunt server
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt/bin/grunt:13:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)

Somebody can give me any idea to fix it?

**Comment by shama** [comment]
Which version of Node.js do you have installed? Could you post the relevant parts of your Gruntfile?

**Comment by HogiQuin** [comment]
Sorry, I diidn't have grunt installed, LOL! I just type 

> npm install -g grunt 

and this run! 

Thanks
