### ISSUE TITLE
The error on installing grunt with npm

### ISSUE THREAD

**Issue by JacobWay** [gruntjs/grunt#1582]
The error occured when I installed the grunt with npm. From the error information, it seems that lwip installation failed by node-gyp.
Then, I tried to install lwip, and it failed, too.

The below is the error when I installed grunt. Any help?

```
➜  coinbitRank git:(master) ✗ npm install grunt --save-dev
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.

> lwip@0.0.9 install /Users/weiqiang/project/activity/coinbitRank/node_modules/lwip
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/util.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/buffer_worker.o
../src/decoder/buffer_worker.cpp:8:56: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    _height(0), _channels(0), _trans(false), _metadata("") {
                                                       ^
1 warning generated.
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/jpeg_decoder.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/png_decoder.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/gif_decoder.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemnobs.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jcomapi.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdapimin.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdapistd.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdatadst.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdatasrc.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdcoefct.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdcolor.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jddctmgr.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdhuff.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdinput.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmainct.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmarker.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmaster.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdpostct.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdsample.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jerror.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctflt.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctfst.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctint.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctflt.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctfst.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctint.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jutils.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemmgr.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdarith.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmerge.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jaricom.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jquant1.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jquant2.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/png.o
In file included from ../src/lib/png/png.c:14:
../src/lib/png/pngpriv.h:805:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
#  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
   ^
1 error generated.
make: *** [Release/obj.target/lwip_decoder/src/lib/png/png.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/weiqiang/.nvm/versions/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Users/weiqiang/.nvm/versions/node/v7.7.3/bin/node" "/Users/weiqiang/.nvm/versions/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/weiqiang/project/activity/coinbitRank/node_modules/lwip
gyp ERR! node -v v7.7.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
coinbitrank@1.0.0 /Users/weiqiang/project/activity/coinbitRank
└── grunt@1.0.1

npm WARN coinbitrank@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lwip@0.0.9 (node_modules/lwip):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lwip@0.0.9 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by shama** [comment]
Weird `lwip` isn't a dependency of `grunt`. What else do you have in your `package.json`?
