### ISSUE TITLE
nodemon error

### ISSUE THREAD

**Issue by abdulazizjs** [gruntjs/grunt#1591]
_when i run code with node it runs but with nodemon it does not run `why?

[nodemon] watching: *.* any time, enter `rs`
[nodemon] starting `node server server.js`
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by shama** [comment]
Could you explain how this problem relates to Grunt?

**Comment by abdulazizjs** [comment]
Do I give questions only related to Grunt?

**Comment by shama** [comment]
You're more likely going to get your question answered if you use the appropriate support channels. I recommend stackoverflow.com or if it is in fact an issue related to nodemon, use their issue tracker.
