### ISSUE TITLE
bug(update): realFavicon doesn't work after upgrade Node.js to version 12

### ISSUE THREAD

**Issue by Kristinita** [gruntjs/grunt#1681]
*Originally posted in [**grunt-real-favicon issue tracker**](https://github.com/RealFaviconGenerator/grunt-real-favicon/issues/46). grunt-real-favicon maintainer [**think, that it a Grunt, not specific grunt-real-favicon problem**](https://github.com/RealFaviconGenerator/grunt-real-favicon/issues/46#issuecomment-494281224). Also, look at [**Gulp similar bug**](https://github.com/gulpjs/gulp/issues/2324).*

### 1. Summary

I upgrade Node.js to version 12 → I get bug.

For Node.js 11 grunt-real-favicon successful works for me.

### 2. Environment

+ Operation system:

    + Windows 10 Enterprise LTSB 64-bit EN (local)
    + Ubuntu 14.04.5 LTS (Travis CI)

+ Node.js:

    + 11.15.0 (works)
    + 12.2.0 (doesn't work)

+ grunt-cli 1.2.0
+ grunt 1.0.4
+ grunt-real-favicon 0.2.3

### 3. Files

See [**KiraRealFavicon branch**](https://github.com/Kristinita/SashaGruntDebugging/tree/KiraRealFavicon) of my debugging repository:

+ `travis.yml`:

```yaml
git:
  depth: 1
language: node_js
node_js:
- 11
- 12
install:
- npm install -g grunt-cli
before_script:
- npm install
script:
- grunt realFavicon --verbose

```

+ `Gruntfile.coffee` (copy from [**RealFaviconGenerator**](https://realfavicongenerator.net/)):

```coffee
module.exports = (grunt) ->

    grunt.loadNpmTasks 'grunt-real-favicon'
    grunt.initConfig
        realFavicon:
            favicons:
                src: "kristinita-favicon.png"
                dest: "."
                options:
                    iconsPath: "."
                    html: ["index.html"]
                    design:
                        ios:
                            pictureAspect: "noChange"
                            assets:
                                ios6AndPriorIcons: false
                                ios7AndLaterIcons: false
                                precomposedIcons: false
                                declareOnlyDefaultIcon: true
                            appName: "Kristinita\'s Search"
                        desktopBrowser: {}
                        windows:
                            pictureAspect: "noChange"
                            backgroundColor: "#ffc40d"
                            onConflict: "override"
                            assets:
                                windows80Ie10Tile: false
                                windows10Ie11EdgeTiles:
                                    small: false
                                    medium: true
                                    big: false
                                    rectangle: false
                            appName: "Kristinita\'s Search"
                        androidChrome:
                            pictureAspect: "noChange"
                            themeColor: "#ffffff"
                            manifest:
                                name: "Kristinita\'s Search"
                                startUrl: "https://kristinita.github.io"
                                display: "standalone"
                                orientation: "notSet"
                                onConflict: "override"
                                declared: true
                            assets:
                                legacyIcon: false
                                lowResolutionIcons: false
                        safariPinnedTab:
                            pictureAspect: "blackAndWhite"
                            threshold: 50
                            themeColor: "#d55b9a"
                    settings:
                        scalingAlgorithm: "Mitchell"
                        errorOnImageTooSmall: false
                        readmeFile: false
                        htmlCodeFile: false
                        usePathAsIs: false

    return

```

### 4. Expected behavior

**If** Node.js = 11.15.0:

> The command "grunt realFavicon --verbose" exited with 0.

+ [**Travis CI demo**](https://travis-ci.org/Kristinita/SashaGruntDebugging/jobs/533705258)

### 5. Non-expected behavior

**Else** Node.js = 12.2.0:

    I get a bug:

```js
Loading "real_favicon.js" tasks…ERROR
>> ReferenceError: primordials is not defined
>>   at fs.js:27:26
>>   at req_ (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/natives/index.js:143:24)
>>   at Object.req [as require] (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/natives/index.js:55:10)
>>   at Object.<anonymous> (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/unzip2/node_modules/graceful-fs/fs.js:1:37)
>>   at Module._compile (internal/modules/cjs/loader.js:759:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>>   at Module.load (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>>   at Module.require (internal/modules/cjs/loader.js:666:19)
>>   at require (internal/modules/cjs/helpers.js:16:16)
>>   at Object.<anonymous> (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/unzip2/node_modules/graceful-fs/graceful-fs.js:3:27)
>>   at Module._compile (internal/modules/cjs/loader.js:759:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>>   at Module.load (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>>   at Module.require (internal/modules/cjs/loader.js:666:19)
>>   at require (internal/modules/cjs/helpers.js:16:16)
>>   at Object.<anonymous> (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/unzip2/node_modules/fstream/lib/reader.js:4:10)
>>   at Module._compile (internal/modules/cjs/loader.js:759:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>>   at Module.load (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>>   at Module.require (internal/modules/cjs/loader.js:666:19)
>>   at require (internal/modules/cjs/helpers.js:16:16)
>>   at Object.<anonymous> (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/unzip2/node_modules/fstream/fstream.js:2:18)
>>   at Module._compile (internal/modules/cjs/loader.js:759:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>>   at Module.load (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>>   at Module.require (internal/modules/cjs/loader.js:666:19)
>>   at require (internal/modules/cjs/helpers.js:16:16)
>>   at Object.<anonymous> (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/unzip2/lib/extract.js:6:14)
>>   at Module._compile (internal/modules/cjs/loader.js:759:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>>   at Module.load (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>>   at Module.require (internal/modules/cjs/loader.js:666:19)
>>   at require (internal/modules/cjs/helpers.js:16:16)
>>   at Object.<anonymous> (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/unzip2/unzip.js:4:19)
>>   at Module._compile (internal/modules/cjs/loader.js:759:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>>   at Module.load (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>>   at Module.require (internal/modules/cjs/loader.js:666:19)
>>   at require (internal/modules/cjs/helpers.js:16:16)
>>   at Object.module.exports.init (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/rfg-api/index.js:17:15)
>>   at Object.module.exports (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt-real-favicon/tasks/real_favicon.js:16:32)
>>   at loadTask (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt/lib/grunt/task.js:315:10)
>>   at /home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt/lib/grunt/task.js:351:7
>>   at Array.forEach (<anonymous>:null:null)
>>   at loadTasks (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt/lib/grunt/task.js:350:11)
>>   at Task.task.loadNpmTasks (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt/lib/grunt/task.js:398:5)
>>   at Object.module.exports (/home/travis/build/Kristinita/SashaGruntDebugging/Gruntfile.coffee:3:8)
>>   at loadTask (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt/lib/grunt/task.js:315:10)
>>   at Task.task.init (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt/lib/grunt/task.js:434:5)
>>   at Object.grunt.tasks (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt/lib/grunt.js:111:8)
>>   at Object.module.exports [as cli] (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt/lib/grunt/cli.js:27:9)
>>   at Object.<anonymous> (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt/node_modules/grunt-cli/bin/grunt:44:20)
>>   at Module._compile (internal/modules/cjs/loader.js:759:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>>   at Module.load (internal/modules/cjs/loader.js:628:32)
>>   at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>>   at Module.require (internal/modules/cjs/loader.js:666:19)
>>   at require (internal/modules/cjs/helpers.js:16:16)
>>   at Object.<anonymous> (/home/travis/build/Kristinita/SashaGruntDebugging/node_modules/grunt/bin/grunt:3:1)
>>   at Module._compile (internal/modules/cjs/loader.js:759:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>>   at Module.load (internal/modules/cjs/loader.js:628:32)
>>   at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>>   at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)
>>   at internal/main/run_main_module.js:17:11
Initializing config…OK
Loading "Gruntfile.coffee" tasks…OK
>> No tasks were registered or unregistered.
Running tasks: realFavicon
Warning: Task "realFavicon" not found. Use --force to continue.
Aborted due to warnings.
The command "grunt realFavicon --verbose" exited with 3.
```

+ [**Travis CI demo**](https://travis-ci.org/Kristinita/SashaGruntDebugging/jobs/533705259)

Thanks.

**Comment by axten** [comment]
any updates here?

**Comment by t8skono** [comment]
If grunt-google-cdn is installed, try changing it to grunt-google-cdn2.
