### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by MrHallway0** [gruntjs/grunt#1721]
I am new to Grunt and Node.js so any help would be great, so I'm sorry! I'm on Linux (Gnome Ubuntu 16). Here is what I get when installing it:
```
(xenial)mrhallway@localhost:~$ sudo npm install grunt --save-dev
npm ERR! Linux 4.14.196-16480-g4c6a5a01ae5a
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "grunt" "--save-dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install grunt as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mrhallway/npm-debug.log
```

as it is telling me to here is `/home/mrhallway/npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'grunt',
1 verbose cli   '--save-dev' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose config Skipping project config: /home/mrhallway/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData grunt@^1.3.0
9 silly fetchNamedPackageData grunt
10 silly mapToRegistry name grunt
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/grunt
14 verbose request uri https://registry.npmjs.org/grunt
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:22:00 PM
17 verbose request id 42df6dab8bb1dd8f
18 verbose etag W/"9e0487736c50fadc18099c9ab292dcbd"
19 verbose lastModified Tue, 18 Aug 2020 19:48:46 GMT
20 http request GET https://registry.npmjs.org/grunt
21 http 304 https://registry.npmjs.org/grunt
22 verbose headers { date: 'Mon, 21 Sep 2020 05:22:00 GMT',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'set-cookie': [ '__cfduid=dcc70f1bb2827f79d5cecfac4770eef651600665720; expires=Wed, 21-Oct-20 05:22:00 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
22 verbose headers   'cf-ray': '5d61589218de02d8-SEA',
22 verbose headers   age: '4692',
22 verbose headers   'cache-control': 'public, max-age=300',
22 verbose headers   etag: '"9e0487736c50fadc18099c9ab292dcbd"',
22 verbose headers   'last-modified': 'Tue, 18 Aug 2020 19:48:46 GMT',
22 verbose headers   vary: 'Accept-Encoding',
22 verbose headers   'cf-cache-status': 'HIT',
22 verbose headers   'cf-request-id': '0550b5af4e000002d8e722d200000001',
22 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 verbose headers   server: 'cloudflare' }
23 silly get cb [ 304,
23 silly get   { date: 'Mon, 21 Sep 2020 05:22:00 GMT',
23 silly get     connection: 'keep-alive',
23 silly get     'set-cookie': [ '__cfduid=dcc70f1bb2827f79d5cecfac4770eef651600665720; expires=Wed, 21-Oct-20 05:22:00 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
23 silly get     'cf-ray': '5d61589218de02d8-SEA',
23 silly get     age: '4692',
23 silly get     'cache-control': 'public, max-age=300',
23 silly get     etag: '"9e0487736c50fadc18099c9ab292dcbd"',
23 silly get     'last-modified': 'Tue, 18 Aug 2020 19:48:46 GMT',
23 silly get     vary: 'Accept-Encoding',
23 silly get     'cf-cache-status': 'HIT',
23 silly get     'cf-request-id': '0550b5af4e000002d8e722d200000001',
23 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
23 silly get     server: 'cloudflare' } ]
24 verbose etag https://registry.npmjs.org/grunt from cache
25 verbose get saving grunt to /home/mrhallway/.npm/registry.npmjs.org/grunt/.cache.json
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install grunt as a dependency of itself
43 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
43 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
43 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /home/mrhallway
45 error Linux 4.14.196-16480-g4c6a5a01ae5a
46 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "grunt" "--save-dev"
47 error node v4.2.6
48 error npm  v3.5.2
49 error code ENOSELF
50 error Refusing to install grunt as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]
```

I'm sorry once again...
[npm-debug.log](https://github.com/gruntjs/grunt/files/5253578/npm-debug.log)

**Comment by Falcikas** [comment]
Are you are trying to install grunt in folder which already has a `package.json` file with a project named 'grunt'? 

From whatI understand, this error means that the Node module which you are trying to install as the dependency is actually your project name.

**Comment by MrHallway0** [comment]
@Falcikas thanks!
