### ISSUE TITLE
Grunt fails on the mac with nodejs 21.1.0 version

### ISSUE THREAD

**Issue by nareshgundu23** [gruntjs/grunt#1775]
we are trying to grunt after the npm install, but in gruntfile.js we have below piece of code. I don't see any permission issues with project directories or files.

copy: {
            main: {
                files: [
                {
                        expand: true,
                        mode: true,
                        cwd: './',
                        src: ['./**/*', '!./workspace/**/*', '!./nw/nw_mac/**/*'],
                        dest: 'build/'
                    },
                    {
                        src: './install_config.js',
                        dest: 'build/ugs/lib/'
                    }
                ]
            },

Running "copy:main" (copy) task
[D] Task source: /Users/buildslave/test-workspace/workspace/starter_nodemodules_mac/konyWebStudio/node_modules/grunt-contrib-copy/tasks/copy.js
**Warning: EPERM: operation not permitted, futime Use --force to continue.
Error: EPERM: operation not permitted, futime**
at Object.futimesSync (node:fs:2160:11)
at syncTimestamp (/Users/buildslave/test-workspace/workspace/starter_nodemodules_mac/konyWebStudio/node_modules/grunt-contrib-copy/tasks/copy.js:63:10)
at /Users/buildslave/test-workspace/workspace/starter_nodemodules_mac/konyWebStudio/node_modules/grunt-contrib-copy/tasks/copy.js:100:11
at Array.forEach (<anonymous>)
at /Users/buildslave/test-workspace/workspace/starter_nodemodules_mac/konyWebStudio/node_modules/grunt-contrib-copy/tasks/copy.js:77:20
at Array.forEach (<anonymous>)
at Object.<anonymous> (/Users/buildslave/test-workspace/workspace/starter_nodemodules_mac/konyWebStudio/node_modules/grunt-contrib-copy/tasks/copy.js:74:16)
at Object.<anonymous> (/Users/buildslave/test-workspace/workspace/starter_nodemodules_mac/konyWebStudio/node_modules/grunt/lib/grunt/task.js:252:15)
at thisTask.fn (/Users/buildslave/test-workspace/workspace/starter_nodemodules_mac/konyWebStudio/node_modules/grunt/lib/grunt/task.js:70:16)
at Object.<anonymous> (/Users/buildslave/test-workspace/workspace/starter_nodemodules_mac/konyWebStudio/node_modules/grunt/lib/util/task.js:294:30)

Aborted due to warnings.
+ cd build
+ npm prune --production --scripts-prepend-node-path=auto
npm WARN config production Use `--omit=dev` instead.

**Comment by Krinkle** [comment]
This issue seems unrelated to Grunt. Without more information, this cannot be diagnosed. Please try to isolate the issue first. Feel free to comment further or create a new issue.
