### ISSUE TITLE
unable to run grunt from grunt-cli: No such file or directory - repos

### ISSUE THREAD

**Issue by jplehmann** [gruntjs/grunt#757]
Hello, I'm trying to build angularjs using grunt according to these directions from the cloned dir of angular. http://docs.angularjs.org/misc/contribute#H1_4

```
npm install
sudo npm uninstall -g grunt
sudo npm install -g grunt-cli
grunt package
```

But any invocation of `grunt` yields:

```
$ grunt --help
/Users/john/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/grunt-0.0.6/lib/grunt/project.rb:18:in `open': No such file or directory - repos (Errno::ENOENT)
    from /Users/john/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/grunt-0.0.6/lib/grunt/project.rb:18:in `entries'
    from /Users/john/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/grunt-0.0.6/lib/grunt/project.rb:18:in `generate_files'
    from /Users/john/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/grunt-0.0.6/lib/grunt/server.rb:13:in `block in <class:Server>'
    from /Users/john/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/sinatra-1.3.5/lib/sinatra/base.rb:1356:in `configure'
    from /Users/john/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/grunt-0.0.6/lib/grunt/server.rb:13:in `<class:Server>'
    from /Users/john/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/grunt-0.0.6/lib/grunt/server.rb:2:in `<module:Grunt>'
    from /Users/john/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/grunt-0.0.6/lib/grunt/server.rb:1:in `<top (required)>'
    from /Users/john/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/grunt-0.0.6/bin/grunt:5:in `<top (required)>'
    from /Users/john/.rbenv/versions/1.9.3-p125/bin/grunt:23:in `load'
    from /Users/john/.rbenv/versions/1.9.3-p125/bin/grunt:23:in `<main>'
```

I understand that grunt-cli should be using the grunt installed into the angular directory, but that seems to fail. Thanks for the help.

**Comment by bsodmike** [comment]
+1 Thank you!
