### ISSUE TITLE
Error with findup-sync. Object Gruntfile.js has no method 'flatten'

### ISSUE THREAD

**Issue by programmerdave** [gruntjs/grunt#888]
Hi, I'm on Ubuntu 12.04LTS and trying to use grunt but I get this error when I try to run any grunt tasks. Any ideas?

Running node v0.10.17, grunt-cli v0.1.9, grunt v0.4.1

```
/workspace/Web Client/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33
    }).flatten().uniq().value();
       ^
TypeError: Object Gruntfile.js has no method 'flatten'
    at Object.module.exports [as findup] (/workspace/Web Client/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33:8)
    at Task.task.init (/workspace/Web Client/node_modules/grunt/lib/grunt/task.js:414:16)
    at Object.grunt.tasks (/workspace/Web Client/node_modules/grunt/lib/grunt.js:113:8)
    at Object.module.exports [as cli] (/workspace/Web Client/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:41:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by ilhnctn** [comment]
I faced a similar error and installed modules error log complained of not found. Then removed node_modules an  cleaned the cache as stated above. Now fixed, thanks to all

**Comment by umairsarwar** [comment]
Had the same error today. This is how I solved it:
1. npm cache clean
2. rm -rf node_modules
3. Read http://stackoverflow.com/questions/15444020/cannot-find-module-findup-sync-when-trying-to-run-grunt
